### ISSUE TITLE
wont load.did everything and got this

### ISSUE THREAD

**Issue by Mikewins1** [nobodyme/conky-fsociety#1]
root@kali:~# cd ~/.conky/conky-fsociety/
root@kali:~/.conky/conky-fsociety# ls
clocks.lua  fsocietyrc  mr.robot.png
root@kali:~/.conky/conky-fsociety# ./fsocietyrc 
./fsocietyrc: line 2: background: command not found
./fsocietyrc: line 3: update_interval: command not found
./fsocietyrc: line 5: cpu_avg_samples: command not found
./fsocietyrc: line 6: net_avg_samples: command not found
./fsocietyrc: line 8: override_utf8_locale: command not found
./fsocietyrc: line 10: double_buffer: command not found
./fsocietyrc: line 11: no_buffers: command not found
./fsocietyrc: line 13: text_buffer_size: command not found
./fsocietyrc: line 14: imlib_cache_size: command not found
./fsocietyrc: line 17: own_window: command not found
./fsocietyrc: line 18: own_window_class: command not found
./fsocietyrc: line 19: own_window_type: command not found
./fsocietyrc: line 20: own_window_argb_visual: command not found
./fsocietyrc: line 21: own_window_argb_value: command not found
./fsocietyrc: line 22: own_window_hints: command not found
./fsocietyrc: line 24: border_inner_margin: command not found
./fsocietyrc: line 26: own_window_transparent: command not found
./fsocietyrc: line 27: own_window_colour: command not found
./fsocietyrc: line 28: minimum_size: command not found
./fsocietyrc: line 29: maximum_width: command not found
./fsocietyrc: line 30: alignment: command not found
./fsocietyrc: line 31: gap_x: command not found
./fsocietyrc: line 32: gap_y: command not found
./fsocietyrc: line 35: draw_shades: command not found
./fsocietyrc: line 36: draw_outline: command not found
./fsocietyrc: line 37: draw_borders: command not found
./fsocietyrc: line 38: draw_graph_borders: command not found
./fsocietyrc: line 41: use_xft: command not found
./fsocietyrc: line 42: font: command not found
./fsocietyrc: line 43: xftalpha: command not found
./fsocietyrc: line 44: uppercase: command not found
./fsocietyrc: line 45: default_color: command not found
./fsocietyrc: line 48: lua_load: command not found
./fsocietyrc: line 49: lua_draw_hook_pre: command not found
./fsocietyrc: line 54: TEXT: command not found
./fsocietyrc: line 56: ${voffset -25}${offset 180}${font neuropol:size=20}${time %I:%M}${offset 4}${font Nimbus Mono L:size=11}$uptime: bad substitution
./fsocietyrc: line 57: ${voffset 14}${offset 178}${color #ad1a26}${font Roboto-Italic:size=12}${time %a, }${time %d %b, %y}: bad substitution
./fsocietyrc: line 59: ${offset 122}${voffset 75}${color #FFFFFF}${font Roboto-Medium:size=17}Dw${offset 14}${color #ad1a26}${downspeed wlan0}: bad substitution
./fsocietyrc: line 61: ${offset 118}${voffset 10}${color #FFFFFF}Up${offset 14}${color #ad1a26}${upspeed wlan0}: bad substitution
./fsocietyrc: line 63: ${offset 120}${voffset 5}${font Roboto-Regularsize=12}${color #FFFFFF}TDown${offset 14}${color #00796b}${totaldown wlan0}: bad substitution
./fsocietyrc: line 64: ${offset 72}${voffset 135}${font Roboto-Regular:size=15}${color #FFFFFF}CPU: bad substitution
./fsocietyrc: line 65: ${offset 188}${voffset 35}${font Roboto-Regular:size=8}Core: bad substitution
./fsocietyrc: line 66: ${offset 234}${voffset -13}Core: bad substitution
./fsocietyrc: line 67: ${offset 204}${voffset 2}${cpu cpu1}%: bad substitution
./fsocietyrc: line 68: ${offset 242}${voffset -13}${cpu cpu2}%: bad substitution
./fsocietyrc: line 70: ${offset 90}${voffset 1}${font Roboto-Regular:size=11}: bad substitution
./fsocietyrc: line 71: ${offset 1}: bad substitution
./fsocietyrc: line 72: ${offset 93}${color #ad1a26}[$memperc%]: bad substitution
./fsocietyrc: line 73: ${offset 120}${voffset 2}${color #ffffff}${font Roboto-Bold:size=14}MEM: bad substitution
./fsocietyrc: line 74: ${voffset -20}${offset 230}${font Roboto-Regular:size=11}${color #FFFFFF}: bad substitution
./fsocietyrc: line 75: ${offset 221}${top_mem name 1}${alignr}${top mem 1}: bad substitution
./fsocietyrc: line 76: ${offset 221}${top_mem name 2}${alignr}${top mem 2}: bad substitution
./fsocietyrc: line 77: ${offset 221}${top_mem name 3}${alignr}${top mem 3}: bad substitution
./fsocietyrc: line 78: ${offset 221}${top_mem name 4}${alignr}${top mem 4}: bad substitution
./fsocietyrc: line 87: ${image ~/.conky/conky-fsociety/mr.robot.png -p 280,130 -s 110x110}: bad substitution
root@kali:~/.conky/conky-fsociety#

**Comment by nobodyme** [comment]
Hi.. I'm sorry I didn't notice it earlier!
I'm particularly not sure why you tried to run this way `./fsocietyrc`.
But as suggested in the [README](https://github.com/nobodyme/conky-fsociety#run). You're supposed to run it like this `conky -c ~/.conky/conky-fsociety/fsocietyrc` or in your case `conky -c fsocietyrc`

You tried this too and didn't work?

If you did, may I know if the default conky worked for you?
If not let me know the OS and DE you are currently using.

**Comment by nobodyme** [comment]
Closed due to no response.
